### ISSUE TITLE
Problems using curl for upload files

### ISSUE THREAD

**Issue by dadez** [Freshman-tech/file-upload#2]
I didn't found how to upload a pdf file using curl, it works well with images, but not with pdf's
I stuck in the content-type check, this one is always `text/plain` instead of `application/pdf` for example.
any hint ?

**Comment by ayoisaiah** [comment]
@dadez It works for me with the following command: `curl -F 'file=@/home/ayo/sample.pdf' http://localhost:4500/upload`. I get `application/pdf` as expected

**Comment by dadez** [comment]
Hi @ayoisaiah , thanks for the quick answer.
I have tried on my professional notebook, and it works, something seems to be wrong on my side.
My apologies for the inconvenience
